import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#671e00",
        outline: "#a78b7d",
        "surface-bright": "#393939",
        "tertiary-fixed-dim": "#ffb59c",
        "on-primary-fixed-variant": "#773300",
        "surface-container-highest": "#353535",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#5c1900",
        "primary-container": "#ff7a1a",
        "error-container": "#93000a",
        "surface-variant": "#353535",
        primary: "#ffb68e",
        "secondary-container": "#d48300",
        secondary: "#ffb867",
        "on-secondary": "#482900",
        error: "#ffb4ab",
        "on-background": "#e5e2e1",
        "secondary-fixed-dim": "#ffb867",
        "surface-dim": "#131313",
        "on-secondary-container": "#452800",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed-dim": "#ffb68e",
        "surface-container": "#20201f",
        tertiary: "#ffb59c",
        "outline-variant": "#584236",
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1c1b1b",
        "on-error": "#690005",
        "on-surface-variant": "#e0c0b1",
        surface: "#131313",
        "tertiary-container": "#ff7846",
        "on-tertiary-fixed-variant": "#822800",
        "on-secondary-fixed": "#2b1700",
        "primary-fixed": "#ffdbca",
        "inverse-primary": "#9c4500",
        "tertiary-fixed": "#ffdbcf",
        "on-primary-container": "#5e2700",
        "secondary-fixed": "#ffddbb",
        "surface-tint": "#ffb68e",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#331200",
        "on-primary": "#542200",
        background: "#131313",
        "on-secondary-fixed-variant": "#673d00",
        "on-tertiary-fixed": "#390c00",
        "on-surface": "#e5e2e1",
        "custom-bg": "#0A0A0A",
        "custom-card": "#1A1A1A",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-xl": "64px",
        gutter: "16px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "stack-sm": "8px",
        "margin-desktop": "40px",
        "stack-xs": "4px",
        "max-width": "1200px",
      },
      fontFamily: {
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-md": ["var(--font-anybody)", "Anybody", "sans-serif"],
        "display-lg-mobile": ["var(--font-anybody)", "Anybody", "sans-serif"],
        "body-md": ["var(--font-hanken-grotesk)", "Hanken Grotesk", "sans-serif"],
        "display-lg": ["var(--font-anybody)", "Anybody", "sans-serif"],
        "body-lg": ["var(--font-hanken-grotesk)", "Hanken Grotesk", "sans-serif"],
        "code-snippet": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.0", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "code-snippet": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
};

export default config;
